/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import { GlobalComponents } from 'vue'

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    'MaterialSymbols:arrowBackIosNewRounded': typeof import('~icons/material-symbols/arrow-back-ios-new-rounded')['default']
    'MaterialSymbols:arrowForwardIosNewRounded': typeof import('~icons/material-symbols/arrow-forward-ios-new-rounded')['default']
    'MaterialSymbols:arrowForwardIosRounded': typeof import('~icons/material-symbols/arrow-forward-ios-rounded')['default']
    'MaterialSymbols:closeRounded': typeof import('~icons/material-symbols/close-rounded')['default']
    MaterialSymbolsArrowBackIosNewRounded: typeof import('~icons/material-symbols/arrow-back-ios-new-rounded')['default']
    MdiArrowExpandAll: typeof import('~icons/mdi/arrow-expand-all')['default']
    MdiCalendarMonthOutline: typeof import('~icons/mdi/calendar-month-outline')['default']
    MdiChevronLeft: typeof import('~icons/mdi/chevron-left')['default']
    MdiChevronRight: typeof import('~icons/mdi/chevron-right')['default']
    MdiClose: typeof import('~icons/mdi/close')['default']
    MdiFileImageOutline: typeof import('~icons/mdi/file-image-outline')['default']
    MdiFormatListBulleted: typeof import('~icons/mdi/format-list-bulleted')['default']
    MdiGoogle: typeof import('~icons/mdi/google')['default']
    MdiImageMultipleOutline: typeof import('~icons/mdi/image-multiple-outline')['default']
    MdiLoading: typeof import('~icons/mdi/loading')['default']
    MdiOpenInNew: typeof import('~icons/mdi/open-in-new')['default']
    MdiOrbit: typeof import('~icons/mdi/orbit')['default']
    MdiPlus: typeof import('~icons/mdi/plus')['default']
    MdiShieldKeyOutline: typeof import('~icons/mdi/shield-key-outline')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}

// For TSX support
declare global {
  const 'MaterialSymbols:arrowBackIosNewRounded': typeof import('~icons/material-symbols/arrow-back-ios-new-rounded')['default']
  const 'MaterialSymbols:arrowForwardIosNewRounded': typeof import('~icons/material-symbols/arrow-forward-ios-new-rounded')['default']
  const 'MaterialSymbols:arrowForwardIosRounded': typeof import('~icons/material-symbols/arrow-forward-ios-rounded')['default']
  const 'MaterialSymbols:closeRounded': typeof import('~icons/material-symbols/close-rounded')['default']
  const MaterialSymbolsArrowBackIosNewRounded: typeof import('~icons/material-symbols/arrow-back-ios-new-rounded')['default']
  const MdiArrowExpandAll: typeof import('~icons/mdi/arrow-expand-all')['default']
  const MdiCalendarMonthOutline: typeof import('~icons/mdi/calendar-month-outline')['default']
  const MdiChevronLeft: typeof import('~icons/mdi/chevron-left')['default']
  const MdiChevronRight: typeof import('~icons/mdi/chevron-right')['default']
  const MdiClose: typeof import('~icons/mdi/close')['default']
  const MdiFileImageOutline: typeof import('~icons/mdi/file-image-outline')['default']
  const MdiFormatListBulleted: typeof import('~icons/mdi/format-list-bulleted')['default']
  const MdiGoogle: typeof import('~icons/mdi/google')['default']
  const MdiImageMultipleOutline: typeof import('~icons/mdi/image-multiple-outline')['default']
  const MdiLoading: typeof import('~icons/mdi/loading')['default']
  const MdiOpenInNew: typeof import('~icons/mdi/open-in-new')['default']
  const MdiOrbit: typeof import('~icons/mdi/orbit')['default']
  const MdiPlus: typeof import('~icons/mdi/plus')['default']
  const MdiShieldKeyOutline: typeof import('~icons/mdi/shield-key-outline')['default']
  const RouterLink: typeof import('vue-router')['RouterLink']
  const RouterView: typeof import('vue-router')['RouterView']
}