/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import { GlobalComponents } from 'vue'

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    'MaterialSymbols:arrowBackIosNewRounded': typeof import('~icons/material-symbols/arrow-back-ios-new-rounded')['default']
    'MaterialSymbols:arrowForwardIosNewRounded': typeof import('~icons/material-symbols/arrow-forward-ios-new-rounded')['default']
    'MaterialSymbols:arrowForwardIosRounded': typeof import('~icons/material-symbols/arrow-forward-ios-rounded')['default']
    'MaterialSymbols:closeRounded': typeof import('~icons/material-symbols/close-rounded')['default']
    MaterialSymbolsArrowBackIosNewRounded: typeof import('~icons/material-symbols/arrow-back-ios-new-rounded')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}

// For TSX support
declare global {
  const 'MaterialSymbols:arrowBackIosNewRounded': typeof import('~icons/material-symbols/arrow-back-ios-new-rounded')['default']
  const 'MaterialSymbols:arrowForwardIosNewRounded': typeof import('~icons/material-symbols/arrow-forward-ios-new-rounded')['default']
  const 'MaterialSymbols:arrowForwardIosRounded': typeof import('~icons/material-symbols/arrow-forward-ios-rounded')['default']
  const 'MaterialSymbols:closeRounded': typeof import('~icons/material-symbols/close-rounded')['default']
  const MaterialSymbolsArrowBackIosNewRounded: typeof import('~icons/material-symbols/arrow-back-ios-new-rounded')['default']
  const RouterLink: typeof import('vue-router')['RouterLink']
  const RouterView: typeof import('vue-router')['RouterView']
}