import type { FirebaseApp } from "firebase/app";
import type { Firestore } from "firebase/firestore";
import type { FirebaseStorage } from "firebase/storage";
import type { ImageRepository } from "./imageRepository";
import { astroImageSchema } from "~/types/image";
import type { AstroImage } from "~/types/image";
import { buildStorageUrl } from "~/composables/useImageUrl";

const GALLERY_COLLECTION_PROD = "images";
const GALLERY_STORAGE_PATH_PROD = "gallery";

const GALLERY_COLLECTION_TEST = "testImages";
const GALLERY_STORAGE_PATH_TEST = "testGallery";

function getPaths(): { collection: string; storagePath: string; thumbnailsPath: string } {
  const config = useRuntimeConfig();
  const isStaging = config.public.appEnv === "staging";
  const storagePath = isStaging ? GALLERY_STORAGE_PATH_TEST : GALLERY_STORAGE_PATH_PROD;
  return {
    collection: isStaging ? GALLERY_COLLECTION_TEST : GALLERY_COLLECTION_PROD,
    storagePath,
    thumbnailsPath: `${storagePath}/thumbnails`,
  };
}

let _app: FirebaseApp | null = null;
let _db: Firestore | null = null;
let _storage: FirebaseStorage | null = null;

async function getFirebaseApp(): Promise<FirebaseApp | null> {
  if (_app) return _app;

  const config = useRuntimeConfig();
  const firebase = config.public.firebase as Record<string, string>;

  if (!firebase.apiKey) return null;

  const { initializeApp, getApps } = await import("firebase/app");
  _app = getApps().length === 0 ? initializeApp(firebase) : getApps()[0];
  return _app;
}

async function getDb(): Promise<Firestore> {
  if (_db) return _db;
  const app = await getFirebaseApp();
  if (!app) throw new Error("Firebase is not configured");
  const { getFirestore } = await import("firebase/firestore");
  _db = getFirestore(app);
  return _db;
}

async function getStorage(): Promise<FirebaseStorage> {
  if (_storage) return _storage;
  const app = await getFirebaseApp();
  if (!app) throw new Error("Firebase is not configured");
  const { getStorage: initStorage } = await import("firebase/storage");
  _storage = initStorage(app);
  return _storage;
}

export class FirebaseImageRepository implements ImageRepository {
  async getAll(): Promise<AstroImage[]> {
    const db = await getDb();
    const { collection, query, orderBy, getDocs } = await import("firebase/firestore");

    const q = query(collection(db, getPaths().collection), orderBy("imageTakenDate", "desc"));
    const snap = await getDocs(q);

    return snap.docs.map((d) => {
      return astroImageSchema.parse({ id: d.id, ...d.data() });
    });
  }

  async getById(id: string): Promise<AstroImage | null> {
    const db = await getDb();
    const { doc, getDoc } = await import("firebase/firestore");
    const docSnapshot = await getDoc(doc(db, getPaths().collection, id));
    return docSnapshot.exists()
      ? astroImageSchema.parse({
          id: docSnapshot.id,
          ...docSnapshot.data(),
        })
      : null;
  }

  async create(image: Omit<AstroImage, "id">): Promise<AstroImage> {
    const db = await getDb();
    const { collection, addDoc } = await import("firebase/firestore");
    const ref = await addDoc(collection(db, getPaths().collection), image);
    return { id: ref.id, ...image };
  }

  async update(id: string, updates: Partial<Omit<AstroImage, "id">>): Promise<AstroImage> {
    const db = await getDb();
    const { doc, updateDoc } = await import("firebase/firestore");
    await updateDoc(doc(db, getPaths().collection, id), updates);
    const updated = await this.getById(id);
    if (!updated) throw new Error(`Image ${id} not found after update`);
    return updated;
  }

  async delete(id: string): Promise<void> {
    const db = await getDb();
    const { doc, deleteDoc } = await import("firebase/firestore");
    await deleteDoc(doc(db, getPaths().collection, id));
  }

  async uploadImage(
    file: File,
    imageId?: string,
  ): Promise<{ cloudLocation: string; thumbnailUrl?: string }> {
    const storage = await getStorage();
    const { ref, uploadBytes } = await import("firebase/storage");

    const filename = `${imageId ?? Date.now()}_${file.name}`;
    const { storagePath, thumbnailsPath } = getPaths();
    const cloudLocation = `${storagePath}/${filename}`;
    const fullRef = ref(storage, cloudLocation);
    await uploadBytes(fullRef, file);

    const config = useRuntimeConfig();
    const storageBucket = (config.public.firebase as Record<string, string>).storageBucket;

    // Thumbnail is generated by a Cloud Function at {storagePath}/thumbnails/{filename}.
    const thumbnailUrl = storageBucket
      ? buildStorageUrl(storageBucket, `${thumbnailsPath}/${filename}`)
      : "";

    return { cloudLocation, thumbnailUrl };
  }
}
